#!/bin/bash
set -e #If any command fails, stop execution of that hook with that error

PHANTOMJS="http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2"

juju-log "Installing $PHANTOMJS."

wget "$PHANTOMJS" 

tar xjf phantomjs-1.9.2-linux-x86_64.tar.bz2
mv phantomjs-1.9.2-linux-x86_64 /usr/local/share 
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs 
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/bin/phantomjs 

juju-log "Fin." 
