#!/bin/bash
#If any command fails, stop execution of the hook with that error
set -e 

SELENIUM_SITE=$(config-get selenium-site)
FIREFOX_SITE=$(config-get firefox-site)
PHANTOMJS_SITE=$(config-get phantomjs-site)

juju-log "Installing Dependencies."
apt-get install -y curl wget python-setuptools openjdk-7-jre xvfb
easy_install pip
pip install --upgrade pip

juju-log "Fetching Selenium From $SELENIUM_SITE"
wget "$SELENIUM_SITE"

juju-log "Installing Selenium Python Client Driver."
pip install -U selenium

juju-log "Fetching PhantomJS from $PHANTOMJS_SITE."
wget "$PHANTOMJS_SITE"

juju-log "Setting up PhantomJS."
tar xjf phantomjs-1.9.2-linux-x86_64.tar.bz2
mv phantomjs-1.9.2-linux-x86_64 /usr/local/share
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
ln -s /usr/local/share/phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

juju-log "Fetching Firefox from $FIREFOX_SITE."
wget "$FIREFOX_SITE"

juju-log "Setting up Firefox."
tar xjf firefox-24.0.tar.bz2
mv firefox /usr/local/share
ln -s /usr/local/share/firefox/firefox /usr/local/bin/firefox
ln -s /usr/local/share/firefox/firefox /usr/bin/firefox

juju-log "Fin."
