#!/bin/bash

juju-log "Starting Virtual Framebuffer."
Xvfb :0 -screen 0 1024x768x8 -extension RANDR
export DISPLAY=:0

juju-log "Starting The Hub Using Port 4444."
java -jar selenium-server-standalone-2.35.0.jar -role hub
curl "http://localhost:4444/wd/hub/status"
