#!/bin/bash

juju-log "Starting Virtual Framebuffer."
Xvfb :0 -screen 0 1024x768x8 -extension RANDR &

juju-log "Starting The Hub Using Port 4444."
/usr/bin/java -jar /usr/local/share/selenium-server-standalone-2.35.0.jar &
#curl "http://127.0.0.1:4444/wd/hub/status"
